name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 145.223.17.13
          username: u500567116
          password: "KyamBCN&dc3xeu>4"
          port: 21
          protocol: ftp
          server-dir: public_html/